{include file="header.tpl" title=foo}

 			<div class="container">
				<div class="nombre_producto"><h3>Consejo para el uso de Armas</h3></div>
				<div>
					<p class="descripcion"> 
					1. MANIPULE LAS ARMAS COMO SI ESTUVIERAN SIEMPRE  CARGADAS.<br><br> 
					2. ANTES DE DISPARAR, ASEGÚRESE DE QUE EL CAÑÓN ESTÉ  LIMPIO Y SIN OBSTRUCCIONES.<br><br>
					3. SIEMPRE GUARDE LAS ARMAS Y SUS MUNICIONES  SEPARADAMENTE, SI ES POSIBLE GUÁRDARLAS BAJO LLAVE Y LEJOS DEL ALCANCE DE LOS NIÑOS O GENTE INEXPERTA.<br><br>
					4. LLEVE A CABO LA TAREA DE APUNTAR CON EL DEDO ÍNDICE FUERA DEL GUARDAMONTE. LLÉVELO AL DISPARADOR SOLO CUANDO EL BLANCO ESTÉ EN EL OBJETIVO.<br><br>
					5. UTILICE  MUNICIONES DE CALIBRE ADECUADO Y PROCEDENCIA CONFIABLE. NO MODIFIQUE  EL MECANISMO DEL ARMA NI LAS MUNICIONES.  LAS REPARACIONES DEBEN SER LLEVADAS A CABO POR SU FABRICANTE O BIEN POR ARMEROS PROFESIONALES.<br><br>
					6. NUNCA PRESTE SU ARMA A NADIE QUE NO ESTÉ FAMILIARIZADO CON SU CORRECTO MANEJO.<br><br>
					7. CUANDO TRANSPORTE ARMAS DEBE MAXIMIZAR LOS CUIDADOS Y EVITAR HACERLO CON EL CARGADOR COLOCADO. VERIFICAR QUE LA RECÁMARA ESTÉ VACÍA, Y UTILIZAR FUNDAS O ESTUCHES.<br><br>
					8. ASEGÚRESE DE QUE EL LUGAR DONDE VA A DISPARAR ESTÉ BIEN DESPEJADO, QUE HAYA UN TOPE SEGURO Y VERIFIQUE LO QUE PUEDA HABER DETRÁS DEL MISMO. RECUERDE QUE EL ALCANCE DEL PROYECTIL SE PROLONGA MUCHO MAS ALLÁ DE LAS DISTANCIAS ÓPTIMAS DE TIRO.<br><br>
					9. UTILICE SIEMPRE EL SEGURO DEL ARMA. NUNCA APUNTE CON EL ARMA CARGADA O DESCARGADA HACIA NINGÚN LUGAR QUE NO SEA SU BLANCO.<br><br>
					10. NO PERMITA EL USO DE ARMAS A MENORES DE EDAD O SI LO HACE, ASEGÚRESE QUE SEA BAJO ESTRICTAS CONDICIONES DE SEGURIDAD.<br><br>
					11. UTILICE  GAFAS Y PROTECTORES AUDITIVOS.<br><br>
					12. NO BEBER ALCOHOL O CONSUMIR ESTUPEFACIENTES ANTES DE DISPARAR. ESTO PODRÍA ALTERAR SU JUICIO Y TIEMPO DE REACCIÓN.<br><br>
					13. EVITE GOLPES EN EL ARMA, ASÍ COMO CAÍDAS Y MOVIMIENTOS BRUSCOS. MÁS AÚN SI ÉSTA SE ENCUENTRA CARGADA.<br><br>
					14. ES IMPORTANTE CONOCER TODAS LAS CARACTERÍSTICAS TÉCNICAS DEL ARMA CON EL CUAL DISPARA.<br><br>
					15. DESCARGAR SIEMPRE LAS ARMAS QUE NO VAN A UTILIZARSE.</p>
				</div>
			</div>

{include file="footer.tpl"}