{include file="header.tpl"}
<article class="articulo_index_principal flota_izq">
		<h2>Fusce ultrices fringilla</h2>
		<p> Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.</p>
		<p> Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.</p>
		<p> Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.</p>
</article>
<aside>
	<article class="articulo_index_aside flota_der" id="noticias">
		<h2>Noticias</h2>
		<p>Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Aliquam erat volutpat. Pellentesque tristique ante ut risus.  </p>
	</article>
	<article class="articulo_index_aside flota_der" id="horario_atencion">
		<h2>Horarios de Atención</h2>
		<p>AAliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. Aliquam erat volutpat. Pellentesque tristique ante ut risus. Quisque dictum. Integer nisl risus, sagittis convallis, rutrum id, elementum congue, nibh. </p>
	</article>
</aside>
{include file="footer.tpl"}